logging:
  level:
    root: info

springdoc:
  show-actuator: false
  api-docs:
    enabled: false

spring:
  autoconfigure:
    exclude: org.springdoc.core.configuration.SpringDocJacksonKotlinModuleConfiguration
