version: '3'

networks:
  network:

volumes:
  dongholab-mysql:
  dongholab-redis:
  dongholab-kafka:
  dongholab-zookeeper-data:
  dongholab-zookeeper-log:

services:
  mysql:
    container_name: dongholab-mysql
    image: ubuntu/mysql:edge
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    networks:
      - network
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=dongholab
      - MYSQL_USER=dongholab
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
    volumes:
      - dongholab-mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
  redis:
    container_name: dongholab-redis
    image: redis:4-alpine
    networks:
      - network
    ports:
      - 6379:6379
    volumes:
      - dongholab-redis:/data
  zookeeper:
    container_name: dongholab-zookeeper
    image: zookeeper:3.7.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: "nc -z localhost 2181 || exit -1"
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - dongholab-zookeeper-data:/var/lib/zookeeper/data
      - dongholab-zookeeper-log:/var/lib/zookeeper/log
    networks:
      - network
  kafka:
    container_name: dongholab-kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - network
